# Generated by Django 6.0 on 2025-12-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Projects')),
                ('description', models.CharField(max_length=255, verbose_name='Descriptions')),
                ('image', models.ImageField(height_field='height_field', upload_to='images/', verbose_name='Images', width_field='width_field')),
                ('height_field', models.PositiveIntegerField()),
                ('width_field', models.PositiveIntegerField()),
                ('links', models.URLField(max_length=255, verbose_name='Git Links')),
                ('technologies', models.CharField(max_length=255, verbose_name='Technogies')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
